import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./(website)/Component/Footer";
import WhatsAppButton from "./(website)/Component/WhatsAppButton";
import { client } from "@/sanity/lib/client";
import { categoriesQuery } from "@/sanity/lib/queries";
import Navbar from "./(website)/Component/Navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

const sourceSansPro = localFont({
  src: [
    {
      path: "../../public/font/source-sans-pro.bold.ttf",
      weight: "700",
      style: "bold", // or "italic" depending on the file's nature
    },
    {
      path: "../../public/font/source-sans-pro.semibold.ttf",
      weight: "600",
      style: "semibold", // or "italic" depending on the file's nature
    },
  ],
  variable: "--font-source-sans",
});

export const metadata: Metadata = {
  title: "Flybeyonz",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${sourceSansPro.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}

