import type { Metadata } from "next";
import Footer from "./Component/Footer";
import WhatsAppButton from "./Component/WhatsAppButton";
import { client } from "@/sanity/lib/client";
import { categoriesQuery } from "@/sanity/lib/queries";
import Navbar from "./Component/Navbar";

export const metadata: Metadata = {
  title: "Flybeyonz",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const categories = await client.fetch(
    categoriesQuery
  );
  return (
    <html
      lang="en"
    >
      <Navbar categories={categories} />
      <body className="min-h-full flex flex-col">{children}</body>
      <WhatsAppButton />
      <Footer />
    </html>
  );
}

